version: '3.2'

networks:
  backend:

services:
  php-fpm:
    build: ./php-fpm-pdo
    depends_on:
      - webserver
      - database
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

  webserver:
    build: ./httpd
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
    ports:
      - 8000:80

  database:
    image: mariadb:latest
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 1234
